apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
            {
              "name": "metadata-listener",
              "image": "alpine",
              "imagePullPolicy": "IfNotPresent",
              "command": [
                "sh", "-c",
                "for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-metadata 8888 && exit 0 || sleep 3; done; exit 1"
              ]
            }
          ]
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: '{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}'
        command: ["/bin/bash","-c","./setup_backend_host.sh && nginx -g 'daemon off;'"]
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: "METADATA_HOST"
          value: {{ .Release.Name }}-metadata
        - name: "APPLIBRARY_HOST"
          value: {{ .Release.Name }}-app-library
{{ if and .Values.galaxy_url .Values.galaxy_api_key }}
        - name: "PORTAL_GALAXY_URL"
          value: {{ .Values.galaxy_url }}
        - name: "PORTAL_GALAXY_API_KEY"
          value: {{ .Values.galaxy_api_key }}
{{ end }}
        - name: "WIKI_HOST"
          value: {{ .Release.Name }}-wiki
        - name: "TSI_PORTAL_URL"
          value: {{ .Values.tsi_portal_url }}
        - name: "AAP_URL"
          value: {{ .Values.aap_url }} 
        - name: "PORTAL_ANNOUNCEMENT"
          value: {{ .Values.portal_announcement }}
        - name: "CLOUD_DEPLOY_GIT_REPO"
          value: {{ .Values.cloud_deploy_git_repo }}
        - name: "ENABLE_HTTPS"
          value: "{{ .Values.enable_https }}"
        ports:
        - containerPort: {{ .Values.frontend.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
