# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# For allowing the Galaxy user creation, a valid galaxy api key and galaxy URL need to be provided.
# helm install --set galaxy_api_key=QWERTYT,galaxy_url="https://publicdev.phenomenal-h2020.eu/" phenomenal/portal
#
# To avoid using persistence on a cluster installation
# helm install --set mysql.persistence.enabled=false phenomenal/portal
#
replicaCount: 1
deployment:
  name: phenomenal-portal
image:
  repository: container-registry.phenomenal-h2020.eu/phnmnl/phenomenal-portal
  tag: latest
service:
  name: http
  type: NodePort
  externalPort: 30766
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
mysql:
  mysqlRootPassword: "backend"
  mysqlUser: "backend-user"
  mysqlPassword: "htgcsak"
  mysqlDatabase: "phenomenal"
backend:
  image: 
     repo: container-registry.phenomenal-h2020.eu/phnmnl/portal-metadata-backend
     tag: latest
  port: 8888
app_library:
  replicaCount: 1
  deployment:
    name: phenomenal-portal-app-library
  image:
    repository: container-registry.phenomenal-h2020.eu/phnmnl/phenomenal-portal-app-library
    tag: latest
  service:
    name: http
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
wiki:
  replicaCount: 1
  deployment:
    name: phenomenal-portal-wiki
  image:
    repository: container-registry.phenomenal-h2020.eu/phnmnl/phenomenal-portal-wiki
    tag: latest
  service:
    name: http
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi


